### ISSUE TITLE
Uncaught ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by Pines-Cheng** [jsdom/webidl-conversions#38]
In Chrome version 92. SharedArrayBuffer has been turned off by default starting that version. Find out more information here: https://developer.chrome.com/blog/enabling-shared-array-buffer/

**Comment by CrimsonCodes0** [comment]
Firefox has had the same restriction for some time too.

Possible workaround (depending on how SAB ctor is used) might be to snatch it from a Wasm heap object:
```js
const SharedArrayBuffer = globalThis.SharedArrayBuffer
  ?? new WebAssembly.Memory({
    initial: 0,
    maximum: 0,
    shared: true
  }).buffer.constructor;

**Comment by daviemakz** [comment]
I am also having issues with this. Currently using version 6.0.0 instead via package.json resolutions, which works over 6.1.0. +1 for a fix!

**Comment by domenic** [comment]
jsdom and its dependent packages (like webidl-conversions) are intended for a Node.js environment. If you want to run in browsers, those browsers must support the same features as Node.js, like SharedArrayBuffer. As such, Safari is not supported at all, and Chrome/Firefox require the cross-origin isolation headers to be set on your site.

That said, it might be worthwhile making this work anyway, since it's probably not that hard. We'd just make `allowShared` a no-op in such environments.

**Comment by joriewong** [comment]
[disabled at the start of 2018](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements)

**Comment by joriewong** [comment]
it's a breaking change!upgrade package is still not working.
